services:
  hom-bot:
    container_name: hom-bot
    build:
      context: .
      dockerfile: dockerfile.dev
    env_file:
      - ./.env
    volumes:
      - ./hom:/wise-old-man/hom-bot/hom
      - ./requirements.txt:/wise-old-man/hom-bot/requirements.txt:ro
      - hom-bot-venv:/wise-old-man/hom-bot/.venv
    command: sh -c ".venv/bin/pip3 install -r requirements.txt && nodemon -e py -w hom -x '.venv/bin/python3 -m hom'"

volumes:
  hom-bot-venv:
