FROM python:3.11.7-slim-bullseye
WORKDIR /wise-old-man/hom-bot

# Project files
COPY hom .
COPY requirements.txt .

# Install dependencies
RUN python3 -m venv .venv
RUN .venv/bin/pip3 install -r requirements.txt

# Run the bot
RUN .venv/bin/python3 -m hom
